[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "pre-commit>=2.20.0",
]

[project]
name = "viv"
version = "22.12a1"
description = "viv isn't venv"
authors = [{ name = "Daylin Morgan", email = "daylinmorgan@gmail.com" }]
dependencies = []
requires-python = ">= 3.7"
readme = "README.md"
license = { text = "MIT" }

[project.scripts]
viv = "viv.viv:main"


[build-system]
requires = ["pdm-pep517>=1.0"]
build-backend = "pdm.pep517.api"
