#!/usr/bin/env python3
"""
Proof of concept output for a 'shim generator'
that would essentially emulate pipx

A possible cli signature

viv shim black -o ~/bin/black
"""

import sys

sys.path.append("/home/daylin/.viv/src")  # noqa
import subprocess
import viv

if __name__ == "__main__":
    vivenv = viv.use(
        "black==23.3.0",
        "click==8.1.3",
        "mypy-extensions==1.0.0",
        "packaging==23.1",
        "pathspec==0.11.1",
        "platformdirs==3.5.1",
    )
    sys.exit(
        subprocess.run(
            [
                vivenv.path / "bin" / "black",
                *sys.argv[1:],
            ]
        ).returncode
    )
