name: GitHub Pages

on:
  push:
    tags: ["v*.*"]
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.11
          cache: true

      - name: Setup Project
        run: pdm install

      - name: Build Docs
        run: pdm run make docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: viv.dayl.in 
          publish_dir: ./site
