name: 🚀 Release

on:
  push:
    tags:
      - 'v*.*'

permissions:
  contents: write

jobs:
  build-n-publish:
    permissions:
      id-token: write
    uses: ./.github/workflows/pypi.yml

  create-release:
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: update latest tag
        uses: richardsimko/update-tag@v1
        with:
          tag_name: latest

      - name: Generate New Release
        run: |
          gh release create ${{ github.ref }}
