name: 🚀 Release

on:
  push:
    tags:
      - 'v*.*'

permissions:
  contents: write

jobs:
  run-tests:
    uses: ./.github/workflows/test.yml

  build-n-publish:
    needs: run-tests
    permissions:
      id-token: write
    uses: ./.github/workflows/pypi.yml

  create-release:
    needs: build-n-publish
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: update latest branch
        run: |
          git checkout -B latest
          git push --force-with-lease -u origin latest

      - name: Generate New Release
        run: gh release create ${{ github.ref }}
